### PR TITLE
Update to liquid-ajax-cart 1.6.0 and bug fix due to Shopify issue.

### PR DESCRIPTION
**Pull request by EvgeniyMukhamedjanov**
Update to liquid-ajax-cart 1.6.0
Replace item.key with item index where it is needed to avoid shopify bug,
Add settings for liquid-ajax-cart

### CODE REVIEW

**Review by Sanj718 — COMMENTED** [review]
@EvgeniyMukhamedjanov why not to keep ajax-cart inside sections folder? since its a section technically.

**Comment by EvgeniyMukhamedjanov** [comment]
@Sanj718 We can, but in my mind it doesn't have relation to a specific section because:
* it is attached not in a section file, but in the common.js
* 99% it will have relation to more than one section (side-cart, cart-page and logically PDP because it ajaxifies product form)
* most likely we will need to create a real .js file for side-cart section. For example where we will put a js code for slider promo within a side-cart?

**Comment by EvgeniyMukhamedjanov** [comment]
@Sanj718 Let me know about your decision of the library, I'll update in case we need to put in back in the sections folder

**Comment by Sanj718** [comment]
> @Sanj718 Let me know about your decision of the library, I'll update in case we need to put in back in the sections folder

Yes agree, i guess you will eventually move it to npm and we gonna remove this file at all. Thanks for the updates.

**Review by Sanj718 — APPROVED** [review]
Approved then!

**Pull request merged**
